name: OWASP ZAP Scan

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan Website with OWASP ZAP

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract URL from Code
        id: extract_url # Le damos un ID al paso para referenciar sus salidas
        run: |
          # --- Elige UNA de las siguientes opciones y borra o comenta las otras ---

          # Opción A: Para archivos .env (o similares)
          # Reemplaza 'DEPLOY_URL=' y '.env' con tu clave y nombre de archivo
          #URL_VALUE=$(grep 'DEPLOY_URL=' .env | cut -d '=' -f 2- | tr -d '"')

          # Opción B: Para archivos JSON
          # Reemplaza '.deployment.targetUrl' y 'config.json' con tu selector y nombre de archivo
          # URL_VALUE=$(jq -r '.deployment.targetUrl' config.json)
          
          # Opción C: Para archivos de texto simple
          # Reemplaza 'url.txt' con el nombre de tu archivo
          URL_VALUE=$(cat url.txt)

          # --- No modifiques las siguientes líneas ---
          if [ -z "$URL_VALUE" ]; then
            echo "Error: No se pudo extraer la URL del archivo de código."
            exit 1
          fi
          echo "URL extraída: $URL_VALUE"
          echo "URL_TO_SCAN=$URL_VALUE" >> $GITHUB_ENV

      - name: Create ZAP directory and Set Permissions
        run: |
          mkdir -p ./zap/wrk
          sudo chmod -R 777 ./zap/wrk

      - name: Run ZAP Scan
        run: |
          echo "Iniciando escaneo ZAP en la URL extraída del código: ${{ env.URL_TO_SCAN }}"

          docker run --rm \
            -v $(pwd)/zap/wrk:/zap/wrk:rw \
            zaproxy/zap-stable zap-baseline.py \
            -t ${{ env.URL_TO_SCAN }} \
            -g gen.conf \
            -r report.html || echo "ZAP scan found vulnerabilities or an error occurred. Exit code: $?"

      - name: Upload ZAP Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ZAP-Report
          path: ./zap/wrk/report.html
          retention-days: 7
