name: OWASP ZAP Scan

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan Website with OWASP ZAP

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract URL from Code
        id: extract_url
        run: |
          # --- Elige UNA de las siguientes opciones y borra o comenta las otras ---

          # Opción A: Para archivos .env (o similares)
          # Reemplaza 'DEPLOY_URL=' y '.env' con tu clave y nombre de archivo
          #URL_VALUE=$(grep 'DEPLOY_URL=' .env | cut -d '=' -f 2- | tr -d '"')

          # Opción B: Para archivos JSON
          # Reemplaza '.deployment.targetUrl' y 'config.json' con tu selector y nombre de archivo
          # URL_VALUE=$(jq -r '.deployment.targetUrl' config.json)
          
          # Opción C: Para archivos de texto simple
          # Reemplaza 'url.txt' con el nombre de tu archivo
          URL_VALUE=$(cat url.txt)

          # --- No modifiques las siguientes líneas ---
          if [ -z "$URL_VALUE" ]; then
            echo "Error: No se pudo extraer la URL del archivo de código."
            exit 1
          fi
          echo "URL extraída: $URL_VALUE"
          echo "URL_TO_SCAN=$URL_VALUE" >> $GITHUB_ENV

      - name: Get Timestamp
        id: timestamp
        run: echo "TIMESTAMP=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV

      - name: Create ZAP directory and Set Permissions
        run: |
          mkdir -p ./zap/wrk
          sudo chmod -R 777 ./zap/wrk

      # --- PASO MODIFICADO PARA EJECUTAR ESCANEO Y MOSTRAR RESUMEN ---
      - name: Run ZAP Scan and Print Summary
        run: |
          # Usamos .md para un reporte legible en la consola
          REPORT_NAME="report-${{ env.TIMESTAMP }}.md"
          
          echo "Iniciando escaneo ZAP en la URL: ${{ env.URL_TO_SCAN }}"
          echo "El informe se guardará como: $REPORT_NAME"
          
          # Evita que el script termine inmediatamente si ZAP encuentra vulnerabilidades
          set +e

          # Ejecuta el escaneo ZAP
          docker run --rm \
            -v $(pwd)/zap/wrk:/zap/wrk:rw \
            zaproxy/zap-stable zap-full-scan.py \
            -t ${{ env.URL_TO_SCAN }} \
            -g gen.conf \
            -r $REPORT_NAME
          
          # Guarda el código de salida de ZAP
          ZAP_EXIT_CODE=$?
          
          # Re-activa la salida en caso de error para los siguientes comandos
          set -e

          # Imprime el resumen del reporte directamente en el log de la acción
          echo "----------------------------------------"
          echo "         RESUMEN DE ALERTAS ZAP         "
          echo "----------------------------------------"
          if [ -f "./zap/wrk/$REPORT_NAME" ]; then
            cat "./zap/wrk/$REPORT_NAME"
          else
            echo "El archivo de reporte no fue encontrado."
          fi
          echo "----------------------------------------"
          
          # Termina el script con el código de salida original de ZAP
          echo "El escaneo ZAP finalizó con el código de salida: $ZAP_EXIT_CODE"
          exit $ZAP_EXIT_CODE

      # --- PASO MODIFICADO PARA SUBIR EL REPORTE CORRECTO ---
      - name: Upload ZAP Report
        if: always() # Se ejecuta incluso si el paso anterior falla
        uses: actions/upload-artifact@v4
        with:
          name: ZAP-Report-${{ env.TIMESTAMP }}
          # Asegúrate de que la ruta coincida con el nombre del reporte (.md)
          path: ./zap/wrk/report-${{ env.TIMESTAMP }}.md
          retention-days: 7
